### ISSUE TITLE
Scoped styles

### ISSUE THREAD

**Issue by mtorromeo** [thgh/rollup-plugin-vue2#12]
Hi,
do you think you can implement support for [scoped styles](https://github.com/vuejs/vue-loader/blob/1fc953aff2c84956404224332d5fbc7176d5ef0f/docs/en/features/scoped-css.md)?

Thanks!

**Comment by thgh** [comment]
I have no intention to implement it, but would accept a PR to add support for it.

CSS support has been separated into another plugin so this feature might involve bringing that back.

**Comment by thgh** [comment]
To be reopened if someones working on it!
