### ISSUE TITLE
Support for lang="" in script, style, and template.

### ISSUE THREAD

**Issue by crueber** [thgh/rollup-plugin-vue2#14]
I really like what you've got going on here! I was wondering if you had any intent to implement alternate lang's for the components? For example...

```vue
<template lang="pug">
#app
  img(src='./assets/logo.png')
  h1 {{ msg }}
</template>

<script lang="coffee">
App = 
  name: 'app'
  data: ->
    msg: 'Welcome to Your Vue.js App!!'
export default App
</script>

<style lang="stylus">
#app
  text-align: center
  color: #2c3e50
  margin-top: 60px
</style>
```

**Comment by thgh** [comment]
I consider splitting the components in separate modules as if they were source imports. By mapping the lang's to file extensions of those modules, other plugins can than handle these. That would be the simplest solution. Not sure if it would work as expected though.

Another option is to include support for every lang in the vue plugin and require() the correct compiler if alternate lang's are found. Ideally it suggests to install the compiler if necessary.

But in the short term, this is not on my todo list.

**Comment by thgh** [comment]
To be reopened if someones working on it!
