### ISSUE TITLE
Purpose

### ISSUE THREAD

**Issue by oligot** [thgh/rollup-plugin-vue2#15]
Hi,

I just wanted to know: what is the purpose of this project, given that there is already [another rollup plugin for Vue.js](https://github.com/znck/rollup-plugin-vue) ?
Wouldn't it be possible to merge the two projects so that there is only one rollup plugin for Vue ?

cc @znck

**Comment by znck** [comment]
Yes, it is possible to merge and better transfer to vuejs organisation. 

@yyx990803 What do you say? Is it possible to add [rollup-plugin-vue](http://github.com/znck/rollup-plugin-vue) to same league as vueify and vue-loader?

**Comment by oligot** [comment]
Having a unified rollup plugin managed by the vuejs organisation would be amazing !

**Comment by yyx990803** [comment]
I'd love to accommodate this project under the organization, although merging and moving seems to be two separate issues.

How would the merge between the two versions work? Using a new major version for `rollup-plugin-vue`?

**Comment by znck** [comment]
Both `rollup-plugin-vue` and `rollup-plugin-vue2` are supporting same features. I suggest to transfer one of these repository to the organisation and use `rollup-plugin-vue` package name for npm.

/ping @thgh

**Comment by yyx990803** [comment]
Ah, I was under the impression that `rollup-plugin-vue` still only support Vue 1, sorry!

So what is the difference between the two plugins at this moment? It seems to make a lot of sense to merge the two.

**Comment by znck** [comment]
Only difference is **how styles are handled?** `rollup-plugin-vue2` injects styles as dependencies [see](https://github.com/thgh/rollup-plugin-vue2/blob/master/src/vueTransform.js#L38) and `rollup-plugin-vue` collects all styles and passes the array to `css` function (which user can override).

**Comment by yyx990803** [comment]
Maybe after the merge this could be configured via an extra option? e.g. `styleToImports: true`

**Comment by znck** [comment]
Yes, it can be done. I'll add that today itself.

**Comment by znck** [comment]
Added option `styleToImports: true`, `rollup-plugin-vue` has all features offered by `rollup-plugin-vue2`.
(See [#45](https://github.com/znck/rollup-plugin-vue/pull/45) on `rollup-plugin-vue`)

Now,  @thgh can abandon `rollup-plugin-vue2`

**Comment by yyx990803** [comment]
@znck that's great, although let's make sure to acknowledge @thgh for his work in contributing an alternative solution :)

**Comment by znck** [comment]
Yes, @thgh is already in credits. :+1:

**Comment by thgh** [comment]
Hey, I agree there should be 1 tool for the job and it's `rollup-plugin-vue` because it has more options and supports both Vue versions. Perfect for to the vuejs organisation. I could add a link to the readme.

The purpose of this project was not only Vue 2 support, The idea was to make the lightest/fastest possible Vue 2 development workflow without config. So I wish to keep developing this plugin. If a namechange is required to avoid confusion, that's ok 👍
