### ISSUE TITLE
[feature request] Src Imports

### ISSUE THREAD

**Issue by QingWei-Li** [thgh/rollup-plugin-vue2#2]
Nice plugin!
Will you consider supporting the feature of src import?
Likes https://github.com/vuejs/vue-loader/blob/7a498297e2ab9d34f210e20057e2d12af0c05a63/docs/en/start/spec.md#src-imports

**Comment by thgh** [comment]
Thanks, good idea!

Will you consider adding support? I think it's pretty doable for styles and scripts. For templates it will be somewhat more difficult.

**Comment by thgh** [comment]
Should work now! Let me know if it doesn't work as expected ;-)

**Comment by QingWei-Li** [comment]
Awesome! I will try it!
