### ISSUE TITLE
How did you know the script cannot be valid?

### ISSUE THREAD

**Issue by Misaka-0x447f** [thgh/rollup-plugin-vue2#23]
https://github.com/thgh/rollup-plugin-vue2/blob/6d37f351707e439b9b812a1f657e799f49e11599/src/index.js#L74-L79

what if use class style component?

**Comment by thgh** [comment]
This plugin is really barebones, it only supports exports like this `/export\s+default\s+\{/` 

The `exportOffset` represents the position where the template can be inserted. It's not possible to write `export default {` in less than 16 characters, so the code in question writes it for you.

Check out rollup-plugin-vue for all-in-one support.

**Comment by Misaka-0x447f** [comment]
Got it, thanks.
