### ISSUE TITLE
Failed to mount component: template or render function not defined.

### ISSUE THREAD

**Issue by MiYogurt** [thgh/rollup-plugin-vue2#6]
hi ! brother, why i use babel compile my code ,vue always give me an error: 
```
Failed to mount component: template or render function not defined.
```
today i leaning rollup,i want try use rollup.js pack vue.js。

```
// rollup.config.js
......
		vue(),
		// css(),
		postcss(),
		resolve({
			jsnext: true,
			main: true,
			browser: true
		}),
		commonjs(),
		json(),
		replace({
			exclude: 'node_modules/**',
			ENV: JSON.stringify(process.env.NODE_ENV || 'development')
		}),
		babel({
			exclude: ['node_modules/**', 'src/style/**']
		}),
		// buble(),
......
```

```
// main.js

import Vue from 'vue';
// import Vue from 'vue/dist/vue.js';

// new Vue({
//     render : (h) => {
//       return h(App)
//     }
// }).$mount('#app');

var vm = new Vue({
  el: '#app',
  render: h => h(App)
})

```

when i use `buble` , whatever i use `'vue'` or `'vue/dist/vue.js'` or `$mount('#app')`  or `el: '#app',`

it work.

but when i try babel. everything is not work.

**Comment by MiYogurt** [comment]
https://github.com/MiYogurt/learn_rollup

all code in here

**Comment by thgh** [comment]
Some pointers:
- Only load serve & livereload in combination with --watch
- Exclude css from buble: `buble({exclude: '**/*.css'}),`
- Do not import from package.json, it's not a module. I think require() would work fine.

Also note:
- Do not import vue/dist/vue.js
- Use babel OR buble
- You might want to start from https://github.com/thgh/vuejs-templates-rollup
